using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SpeakEase.RabbitMq.Sourcegenerate
{
    [Generator]
    public class ConsumerSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new ConsumerSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not ConsumerSyntaxReceiver receiver)
                return;

            var consumerClasses = new List<ConsumerClassInfo>();

            foreach (var classDeclaration in receiver.CandidateClasses)
            {
                var semanticModel = context.Compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);
                if (classSymbol == null)
                    continue;

                // 查找 IConsumer<T> 接口
                var consumerInterface = classSymbol.Interfaces
                    .FirstOrDefault(i => i.Name == "IConsumer" && i.TypeArguments.Length == 1);

                if (consumerInterface == null)
                    continue;

                // 从泛型参数获取消息类型
                var messageType = consumerInterface.TypeArguments[0];

                // 检查消息类型是否有 [Consumer] 特性
                var consumerAttribute = messageType.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "ConsumerAttribute");

                if (consumerAttribute == null)
                    continue;

                var classInfo = new ConsumerClassInfo
                {
                    ClassName = classSymbol.Name,
                    MessageType = messageType.ToDisplayString(),
                    FullClassName = classSymbol.ToDisplayString()
                };

                consumerClasses.Add(classInfo);
            }

            // 生成订阅扩展方法
            if (consumerClasses.Count > 0)
            {
                GenerateSubscribeExtensions(context, consumerClasses);
            }
        }

        private void GenerateSubscribeExtensions(GeneratorExecutionContext context, List<ConsumerClassInfo> consumerClasses)
        {
            var sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine("// <auto-generated/>");
            sourceBuilder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sourceBuilder.AppendLine("using SpeakEase.RabbitMq.Interface;");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("namespace SpeakEase.RabbitMq.Extensions");
            sourceBuilder.AppendLine("{");
            sourceBuilder.AppendLine("    /// <summary>");
            sourceBuilder.AppendLine("    /// 消费者订阅扩展方法");
            sourceBuilder.AppendLine("    /// </summary>");
            sourceBuilder.AppendLine("    public static class ConsumerSubscribeExtensions");
            sourceBuilder.AppendLine("    {");
            sourceBuilder.AppendLine("        /// <summary>");
            sourceBuilder.AppendLine("        /// 订阅所有 RabbitMQ 消费者");
            sourceBuilder.AppendLine("        /// </summary>");
            sourceBuilder.AppendLine("        /// <param name=\"serviceProvider\">服务提供者</param>");
            sourceBuilder.AppendLine("        /// <returns>异步任务</returns>");
            sourceBuilder.AppendLine("        public static async Task SubscribeAllConsumersAsync(this IServiceProvider serviceProvider)");
            sourceBuilder.AppendLine("        {");
            sourceBuilder.AppendLine("            var consumerFactory = serviceProvider.GetRequiredService<IConsumerFactory>();");
            sourceBuilder.AppendLine();

            foreach (var classInfo in consumerClasses)
            {
                sourceBuilder.AppendLine($"            // 订阅 {classInfo.ClassName}");
                sourceBuilder.AppendLine($"            await consumerFactory.SubscribeAsync<{classInfo.MessageType}>();");
            }

            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine("    }");
            sourceBuilder.AppendLine("}");

            context.AddSource("ConsumerSubscribeExtensions.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }

        private class ConsumerClassInfo
        {
            public string ClassName { get; set; }
            public string MessageType { get; set; }
            public string FullClassName { get; set; }
        }

        private class ConsumerSyntaxReceiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> CandidateClasses { get; } = new List<ClassDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is ClassDeclarationSyntax classDeclaration)
                {
                    // 检查是否有属性
                    if (classDeclaration.AttributeLists.Count > 0)
                    {
                        CandidateClasses.Add(classDeclaration);
                    }
                }
            }
        }
    }
}
