using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SpeakEase.RabbitMq.Sourcegenerate
{
    [Generator]
    public class InjectSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new InjectSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not InjectSyntaxReceiver receiver)
                return;

            var injectClasses = new List<InjectClassInfo>();

            foreach (var classDeclaration in receiver.CandidateClasses)
            {
                var semanticModel = context.Compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
                if (classSymbol == null)
                    continue;

                // 查找 InjectAttribute
                var injectAttribute = classSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "InjectAttribute");

                if (injectAttribute == null)
                    continue;

                // 读取 ServiceLifetime 属性值
                var lifetimeValue = 1; // 默认为 Scoped
                var lifetimeArg = injectAttribute.NamedArguments
                    .FirstOrDefault(arg => arg.Key == "ServiceLifetime");
                if (lifetimeArg.Key != null)
                {
                    lifetimeValue = (int)lifetimeArg.Value.Value!;
                }

                // 查找实现的接口
                var implementedInterfaces = classSymbol.Interfaces
                    .Where(i => i.DeclaredAccessibility == Accessibility.Public)
                    .ToList();

                var classInfo = new InjectClassInfo
                {
                    ClassName = classSymbol.Name,
                    FullClassName = classSymbol.ToDisplayString(),
                    Lifetime = lifetimeValue,
                    Interfaces = implementedInterfaces.Select(i => i.ToDisplayString()).ToList()
                };

                injectClasses.Add(classInfo);
            }

            // 生成依赖注入扩展方法
            if (injectClasses.Count > 0)
            {
                GenerateServiceExtensions(context, injectClasses);
            }
        }

        private void GenerateServiceExtensions(GeneratorExecutionContext context, List<InjectClassInfo> injectClasses)
        {
            var sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine("// <auto-generated/>");
            sourceBuilder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("namespace SpeakEase.RabbitMq.Extensions");
            sourceBuilder.AppendLine("{");
            sourceBuilder.AppendLine("    /// <summary>");
            sourceBuilder.AppendLine("    /// 自动依赖注入扩展方法");
            sourceBuilder.AppendLine("    /// </summary>");
            sourceBuilder.AppendLine("    public static class InjectServiceExtensions");
            sourceBuilder.AppendLine("    {");
            sourceBuilder.AppendLine("        /// <summary>");
            sourceBuilder.AppendLine("        /// 注册所有带 [Inject] 特性的服务");
            sourceBuilder.AppendLine("        /// </summary>");
            sourceBuilder.AppendLine("        public static IServiceCollection AddInjectServices(this IServiceCollection services)");
            sourceBuilder.AppendLine("        {");

            foreach (var classInfo in injectClasses)
            {
                var lifetimeMethod = classInfo.Lifetime switch
                {
                    0 => "AddSingleton",
                    1 => "AddScoped",
                    2 => "AddTransient",
                    _ => "AddScoped" // 默认
                };

                sourceBuilder.AppendLine($"            // 注册 {classInfo.ClassName} ({GetLifetimeName(classInfo.Lifetime)})");

                // 如果有接口，注册接口映射
                if (classInfo.Interfaces.Count > 0)
                {
                    foreach (var interfaceType in classInfo.Interfaces)
                    {
                        sourceBuilder.AppendLine($"            services.{lifetimeMethod}<{interfaceType}, {classInfo.FullClassName}>();");
                    }
                }
                else
                {
                    // 没有接口，直接注册类型
                    sourceBuilder.AppendLine($"            services.{lifetimeMethod}<{classInfo.FullClassName}>();");
                }
            }

            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("            return services;");
            sourceBuilder.AppendLine("        }");
            sourceBuilder.AppendLine("    }");
            sourceBuilder.AppendLine("}");

            context.AddSource("InjectServiceExtensions.g.cs", SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }

        private static string GetLifetimeName(int lifetime)
        {
            return lifetime switch
            {
                0 => "Singleton",
                1 => "Scoped",
                2 => "Transient",
                _ => "Scoped"
            };
        }

        private class InjectClassInfo
        {
            public string ClassName { get; set; }
            public string FullClassName { get; set; }
            public int Lifetime { get; set; } = 1; // 默认 Scoped
            public List<string> Interfaces { get; set; } = new List<string>();
        }

        private class InjectSyntaxReceiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> CandidateClasses { get; } = new List<ClassDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is ClassDeclarationSyntax classDeclaration)
                {
                    // 检查是否有属性
                    if (classDeclaration.AttributeLists.Count > 0)
                    {
                        CandidateClasses.Add(classDeclaration);
                    }
                }
            }
        }
    }
}
