using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace SpeakEase.RabbitMq.Sourcegenerate
{
    [Generator]
    public class MessageSourceGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new MessageSyntaxReceiver());
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not MessageSyntaxReceiver receiver)
                return;

            foreach (var classDeclaration in receiver.CandidateClasses)
            {
                var semanticModel = context.Compilation.GetSemanticModel(classDeclaration.SyntaxTree);
                var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
                if (classSymbol == null)
                    continue;

                // 查找 ConsumerAttribute
                var consumerAttribute = classSymbol.GetAttributes()
                    .FirstOrDefault(a => a.AttributeClass?.Name == "ConsumerAttribute");

                if (consumerAttribute == null)
                    continue;

                // 读取 ConsumerAttribute 的属性值
                string exchangeName = "";
                string queueName = "";
                string routeKey = "";

                foreach (var arg in consumerAttribute.NamedArguments)
                {
                    switch (arg.Key)
                    {
                        case "ExchangeName":
                            exchangeName = arg.Value.Value?.ToString() ?? "";
                            break;
                        case "QueueName":
                            queueName = arg.Value.Value?.ToString() ?? "";
                            break;
                        case "RouteKey":
                            routeKey = arg.Value.Value?.ToString() ?? "";
                            break;
                    }
                }

                // 生成分部类
                GeneratePartialClass(context, classSymbol, exchangeName, queueName, routeKey);
            }
        }

        private void GeneratePartialClass(
            GeneratorExecutionContext context,
            INamedTypeSymbol classSymbol,
            string exchangeName,
            string queueName,
            string routeKey)
        {
            var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
            var className = classSymbol.Name;
            var accessibility = classSymbol.DeclaredAccessibility.ToString().ToLower();
            var fullTypeName = classSymbol.ToDisplayString();
        
            var sourceBuilder = new StringBuilder();
            sourceBuilder.AppendLine("// <auto-generated/>");
            sourceBuilder.AppendLine("#nullable enable");
            sourceBuilder.AppendLine("using System.Text.Json.Serialization;");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine($"namespace {namespaceName}");
            sourceBuilder.AppendLine("{");
            sourceBuilder.AppendLine("    /// <summary>");
            sourceBuilder.AppendLine($"    /// 为 {className} 自动实现 IMessage 接口");
            sourceBuilder.AppendLine("    /// </summary>");
            sourceBuilder.AppendLine($"    {accessibility} partial class {className} : SpeakEase.RabbitMq.Interface.IMessage");
            sourceBuilder.AppendLine("    {");
            sourceBuilder.AppendLine("        /// <summary>");
            sourceBuilder.AppendLine("        /// 交换机名称");
            sourceBuilder.AppendLine("        /// </summary>");
            sourceBuilder.AppendLine("        [JsonIgnore]");
            sourceBuilder.AppendLine($"        public string ExchangeName => \"{exchangeName}\";");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("        /// <summary>");
            sourceBuilder.AppendLine("        /// 队列名称");
            sourceBuilder.AppendLine("        /// </summary>");
            sourceBuilder.AppendLine("        [JsonIgnore]");
            sourceBuilder.AppendLine($"        public string QueeuName => \"{queueName}\";");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("        /// <summary>");
            sourceBuilder.AppendLine("        /// 路由键");
            sourceBuilder.AppendLine("        /// </summary>");
            sourceBuilder.AppendLine("        [JsonIgnore]");
            sourceBuilder.AppendLine($"        public string RouteKey => \"{routeKey}\";");
            sourceBuilder.AppendLine();
            sourceBuilder.AppendLine("        /// <summary>");
            sourceBuilder.AppendLine("        /// 消息类型（完全限定名）");
            sourceBuilder.AppendLine("        /// </summary>");
            sourceBuilder.AppendLine("        [JsonIgnore]");
            sourceBuilder.AppendLine($"        public string Type {{ get; set; }} = \"{fullTypeName}\";");
            sourceBuilder.AppendLine("    }");
            sourceBuilder.AppendLine("}");
        
            // 使用类的完全限定名作为文件名，避免命名冲突
            var fileName = $"{classSymbol.ToDisplayString().Replace(".", "_")}.IMessage.g.cs";
            context.AddSource(fileName, SourceText.From(sourceBuilder.ToString(), Encoding.UTF8));
        }

        private class MessageSyntaxReceiver : ISyntaxReceiver
        {
            public List<ClassDeclarationSyntax> CandidateClasses { get; } = new List<ClassDeclarationSyntax>();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is ClassDeclarationSyntax classDeclaration)
                {
                    // 检查是否有属性
                    if (classDeclaration.AttributeLists.Count > 0)
                    {
                        CandidateClasses.Add(classDeclaration);
                    }
                }
            }
        }
    }
}
